version: '3'

services:
  app:
    image: docker-portfolio
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles