version: '3'

services:
  nextjs: 
    build: 
      dockerfile: ./Dockerfile.production
      context: .
    container_name: nextjs_portoflio
    ports:
      - "3000:3000"

  nginx: 
    build: ./nginx
    container_name: nginx_nextjs_portfolio
    ports:
      - "80:80"