version: '3'

services:
  nextjs: 
    build: 
      dockerfile: ./Dockerfile.production
      context: .
    container_name: nextjs
    ports:
      - "3000:3000"

  nginx: 
    build: ./nginx
    ports:
      - "80:80"